
# 1. Exclude files from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# 2. Installed Gems
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts

# 5. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "This is merely a demo, find out more [about Garth](about)" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
remote_theme: daviddarnes/garth
title: The Diary of an AI Practitioner 
email: nnkaranikola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a place to learn all things AI. 
baseurl: "/ai-blog/ " # the subpath of your site, e.g. /blog
url: https://nkkrnkl.github.io  # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
domain: nkkrnkl.github.io 

# Build settings
theme: minima

